### ISSUE TITLE
Support login with just the arm mixin

### ISSUE THREAD

**Issue by carolynvs** [getporter/arm-mixin#45]
I want to be able to authenticate to Azure without using the az mixin. It should be a mixin configuration whether or not authentication occurs automatically.

```yaml
mixins:
- arm:
    autoLogin: true # Automatically log into azure as needed

install:
- arm: 
      description: "This step will automatically authenticate for me"
```

Login with ambient environment variables such as AZURE_CLIENT_ID, etc
```yaml
install:
- arm:
     description: "login"
     login
```

Explicit login
```yaml
install:
- arm:
     description: "login"
     login:
       clientId: "something else"
       clientSecret: "than the default"
       tenantId: "azure environment variables"
```
